version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: ml_playground_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ml_playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer для управления БД (опционально)
  adminer:
    image: adminer
    container_name: ml_playground_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  # Backend приложение
  backend:
    build: .
    container_name: ml_playground_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/ml_playground
      - SECRET_KEY=dev-secret-key-change-in-production-32chars
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./ml_core:/app/ml_core
      - ./data:/app/data
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

networks:
  default:
    name: ml_playground_network
